### ISSUE TITLE
Credentails Exposed

### ISSUE THREAD

**Issue by csquared** [henrycastillome/onlinecoursedjangoapp#1]
https://github.com/henrycastillome/onlinecoursedjangoapp/blob/2d1676eca049e4d9472ad08a2b8bb80753da3f29/onlinecourse/settings.py#L182-L185

Hi there:
Chris from Bucketeer here. These credentials are on the public internet. I've rolled them and new ones are available in your Heroku app - please keep them private in the future!
Cheers,
Chris

**Comment by henrycastillome** [comment]
Hey Thank you.
